/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lcy_Hello */

#ifndef _Included_com_lcy_Hello
#define _Included_com_lcy_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lcy_Hello
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lcy_Hello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif